// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_bbox`, `image_to_tensor`, `non_max_suppression`, `process_output`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DetectionResult`, `YOLO`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `letterbox`, `new_from_mem`, `new`, `predict`

/// Прямоугольник, ограничивающий обнаруженный объект.
///
/// Хранит координаты двух углов: верхнего левого (`x1`, `y1`) и нижнего правого (`x2`, `y2`).
class BoundingBox {
  final double x1;
  final double y1;
  final double x2;
  final double y2;

  const BoundingBox({
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
  });

  Future<double> intersection({required BoundingBox other}) =>
      RustLib.instance.api
          .crateYoloEndoYoloBoundingBoxIntersection(that: this, other: other);

  Future<double> iou({required BoundingBox other}) => RustLib.instance.api
      .crateYoloEndoYoloBoundingBoxIou(that: this, other: other);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BoundingBox> newInstance(
          {required double x1,
          required double y1,
          required double x2,
          required double y2}) =>
      RustLib.instance.api
          .crateYoloEndoYoloBoundingBoxNew(x1: x1, y1: y1, x2: x2, y2: y2);

  Future<double> union({required BoundingBox other}) => RustLib.instance.api
      .crateYoloEndoYoloBoundingBoxUnion(that: this, other: other);

  @override
  int get hashCode => x1.hashCode ^ y1.hashCode ^ x2.hashCode ^ y2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoundingBox &&
          runtimeType == other.runtimeType &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2;
}
