name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^0.13.5
  video_player_win: ^3.1.1
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  video_player: ^2.10.0
  screenshot: ^3.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true