use anyhow::anyhow;
use flutter_rust_bridge::frb;
use image::{ImageBuffer};
use ort::error::Result;
use crate::yolo::YOLO;

// For flutter_rust_bridge autogenerated shit
pub use image::DynamicImage;

#[frb]
#[derive(Debug, Clone)]
pub struct FFIDetectionResult {
    pub x1: f32,
    pub y1: f32,
    pub x2: f32,
    pub y2: f32,
    pub label: String,
    pub confidence: f32,
}

#[frb(opaque)]
pub struct YoloHandle(
     #[frb(ignore)]
     pub YOLO
);

#[frb]
pub fn yolo_new(
    model_path: String,
    class_labels: Vec<String>,
    confidence_threshold: f32,
    nms_threshold: f32,
) -> Result<YoloHandle> {
    let yolo = YOLO::new(
        model_path.as_str(),
        class_labels,
        confidence_threshold,
        nms_threshold
    );
    Ok(YoloHandle(yolo.unwrap()))
}

#[frb]
pub fn yolo_new_mem(
    mem: Vec<u8>,
    class_labels: Vec<String>,
    confidence_threshold: f32,
    nms_threshold: f32,
) -> Result<YoloHandle> {
    let yolo = YOLO::new_from_mem(
        mem.as_slice(),
        class_labels,
        confidence_threshold,
        nms_threshold
    );
    Ok(YoloHandle(yolo.unwrap()))
}

 #[frb]
 pub fn yolo_predict(
     yolo_handle: &mut YoloHandle,
     width: u32,
     height: u32,
     pixels: Vec<u8>
 ) -> Result<Vec<FFIDetectionResult>> {
     // Create image buffer with proper error handling
     let buffer = ImageBuffer::from_raw(width, height, pixels)
     .ok_or_else(|| {
          ort::Error::from(Box::new(
              std::io::Error::new(
                  std::io::ErrorKind::InvalidData, 
                  "Invalid pixel buffer length"
              )
          ) as Box<dyn std::error::Error + Send + Sync>)
      })?;
 
     // Convert to RGB and save debug image
     let img_rgb = DynamicImage::ImageRgba8(buffer).into_rgb8();
     
     // Create DynamicImage from RGB buffer for prediction
     let img_dyn = DynamicImage::ImageRgb8(img_rgb);

    let yolo = &mut yolo_handle.0;
    let dets = yolo.predict(&img_dyn)?;
    let ffi = dets.into_iter()
        .map(|d| FFIDetectionResult{
            x1: d.bbox.x1,
            y1: d.bbox.y1,
            x2: d.bbox.x2,
            y2: d.bbox.y2,
            label: d.label,
            confidence: d.confidence,
        }).collect();
    Ok(ffi)
}


