name: Flutter CI

on:
  push:
    branches: [ main, deploy ]   # normal dev flow
    tags:     [ 'MVPv*' ]        # MVPv1.0.0 etc trigger release job
  pull_request:

jobs:
# -------------------------------------------------------------
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: stable
          cache: true

      - name: Install pub deps
        run: flutter pub get

      - name: Lint (flutter analyze)
        run: flutter analyze --no-pub

      - name: Format check
        run: dart format --output none --set-exit-if-changed .

      # Run all tests but exclude the intentionally failing one
      - name: Run tests (excluding intentional failures)
        run: |
          flutter test --exclude-tags=failing

      # Verify the intentional failure test does fail as expected
      - name: Verify intentional failure test
        run: |
          if flutter test test/failing_test.dart; then
            echo "ERROR: failing_test.dart should fail but passed!"
            exit 1
          else
            echo "✓ failing_test.dart correctly failed as expected"
          fi


      - name: Run integration tests
        run: flutter test integration_test

# -------------------------------------------------------------
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: stable
          cache: true

      # Install Rust for flutter_rust_bridge
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pub deps
        run: flutter pub get


      - name: Format check
        run: dart format --output none --set-exit-if-changed .

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows debug (validation)
        run: flutter build windows --debug

# -------------------------------------------------------------
  release-win:
    if: startsWith(github.ref, 'refs/tags/MVPv')    # fires only on MVPv* tag
    needs: [build-test, build-windows]              # run tests and Windows build first
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          channel: stable

      # Install Rust for flutter_rust_bridge
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pub deps
        run: flutter pub get

      - name: Format check
        run: dart format --output none --set-exit-if-changed .

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows release
        run: flutter build windows --release

      - name: Strip symbols & zip
        run: |
          cd build/windows/x64/runner/Release
          Remove-Item *.pdb,*.ilk -Force -ErrorAction SilentlyContinue
          Compress-Archive -Path * -DestinationPath EndoscopeAI.zip

      - name: Attach artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/x64/runner/Release/EndoscopeAI.zip
          generate_release_notes: true
